{{- if .Values.vpa.enabled }}
apiVersion: "autoscaling.k8s.io/v1"
kind: VerticalPodAutoscaler
metadata:
  name: {{ include "chart.fullname" . }}-vpa
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: {{ include "chart.fullname" . }}
  updatePolicy:
    updateMode: {{ .Values.vpa.updateMode }}
  resourcePolicy:
    containerPolicies:
      - containerName: '*'
        minAllowed:
          cpu: {{ .Values.vpa.minCpu }}
          memory: {{ .Values.vpa.minMemory }}
        maxAllowed:
          cpu: {{ .Values.vpa.maxCpu }}
          memory: {{ .Values.vpa.maxMemory }}
{{- end }}
