# Use an official Debian image.
FROM debian:bullseye-slim

# Install dependencies
RUN apt-get update && \
    apt-get install -y curl ca-certificates bash && \
    update-ca-certificates && \
    curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl" && \
    install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl && \
    apt-get remove --purge --auto-remove -y curl && \
    rm -rf /var/lib/apt/lists/*

# Copy the script into the container
COPY pod_cleaner.sh /pod_cleaner.sh

# Give execution rights to the script
RUN chmod +x /script.sh

# Command to run the script
CMD ["/pod_cleaner.sh"]